# Generated by Django 5.0.6 on 2024-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_role_employee_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('employed', 'Employed'), ('fired', 'Fired')], default='employed', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('scrum_master', 'Scrum Master')], max_length=100, unique=True),
        ),
    ]
